### ISSUE TITLE
האוכל של הנחש יכול לצוץ על גוף שלו

### ISSUE THREAD

**Issue by shl505** [MosheBrizel/Snake-Game#1]
אם זה בכוונה אני לא מתערב, אבל במשחקים שאני שיחקתי זה לא היה ככה.

**Comment by MosheBrizel** [comment]
אפשרי להוסיף את האפשרות שלא יצא על הנחש,
אבל אני לא חושב שזה בעיה שיצא על הנחש.
לפעמים אומרים: 
זה לא באג זה פיצ'ר 😉.

**Comment by MosheBrizel** [comment]
> אם זה בכוונה אני לא מתערב, אבל במשחקים שאני שיחקתי זה לא היה ככה.

אפשרי להוסיף את האפשרות שלא יצא על הנחש,
אבל אני לא חושב שזה בעיה שיצא על הנחש.
לפעמים אומרים:
זה לא באג זה פיצ'ר 😉.
